-- Migration 0004: Approval flow schema — Phase 4 (Telegram Approval Loop)
-- Creates: approval_events table + post_copy column on content_history

-- Section A: approval_events table
-- Append-only log of creator decisions made in the Telegram approval flow.
-- Every approval and rejection is recorded as an immutable event row.
-- This is the restart-safe state store: ApprovalService checks it before
-- re-sending a video so the creator is never asked to act twice on the same content.
--
-- cause_code values (NULL for approvals, required for rejections):
--   'script_error'    — script content is wrong, misleading, or off-brand
--   'visual_error'    — avatar, background, or visual quality is unacceptable
--   'technical_error' — encoding, audio sync, or playback problem
--   'off_topic'       — content drifts from the channel's philosophical focus
--
-- rejection_requires_cause: enforces that every rejected event carries a cause_code.
-- This populates the rejection_constraints table used by the script-generation pipeline
-- in Phase 2 to avoid repeating the same types of rejections.

CREATE TABLE IF NOT EXISTS approval_events (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at          timestamptz DEFAULT now() NOT NULL,
    content_history_id  uuid NOT NULL REFERENCES content_history(id),
    action              text NOT NULL CHECK (action IN ('approved', 'rejected')),
    cause_code          text CHECK (cause_code IN (
                            'script_error',
                            'visual_error',
                            'technical_error',
                            'off_topic'
                        )),
    CONSTRAINT rejection_requires_cause CHECK (
        action = 'approved' OR cause_code IS NOT NULL
    )
);

-- Section B: indexes
-- approval_events_content_history_id_idx supports is_already_actioned() lookup:
--   SELECT id FROM approval_events WHERE content_history_id = $1 LIMIT 1
-- approval_events_created_at_idx supports get_today_rejection_count() date-range query:
--   SELECT count(*) FROM approval_events WHERE action='rejected' AND created_at >= $today

CREATE INDEX IF NOT EXISTS approval_events_content_history_id_idx
    ON approval_events(content_history_id);

CREATE INDEX IF NOT EXISTS approval_events_created_at_idx
    ON approval_events(created_at);

-- Section C: post_copy column on content_history
-- Spanish social media copy generated by PostCopyService (Phase 4).
-- Stored alongside the video record so the publish step (Phase 5) can
-- attach the caption without regenerating it after approval.

ALTER TABLE content_history
    ADD COLUMN IF NOT EXISTS post_copy text;
